### ISSUE TITLE
adjust schedule page

### ISSUE THREAD

**Issue by Ram-Raghav-S** [WCSAorientation/OrientationWebsite2023#18]
The schedule page needs to adjusted according to the [figma design](https://www.figma.com/file/6Qo58U2Vt5NMZ8EGgfusQg/WDW-Orientation-Website?type=design&node-id=0-1&t=lL7hq1hQaOEJPiRW-0).

There is no spacing below the schedule image right now - this needs to be added.

Image for reference: 
![image](https://github.com/WCSAorientation/OrientationWebsite2023/assets/92739966/6e6c3404-c667-4d39-8a04-e23f13120e4a)

**Comment by maheshhbalwan** [comment]
@Ram-Raghav-S The div with the white background on the 'Schedule' page appears to have enough spacing below it based on the provided screenshot. Therefore, I recommend considering the issue closed.

![Screenshot 2023-06-15 054948](https://github.com/WCSAorientation/OrientationWebsite2023/assets/85355816/e7f8008b-2433-4095-bb8a-b23db4bd3303)
